language: python

python:
  - "2.7"
  - "3.4"

env:
  - DJANGO=1.4
  - DJANGO=1.5
  - DJANGO=1.6
  - DJANGO=1.7

matrix:
  exclude:
    - python: "3.4"
      env: DJANGO=1.4

install:
  - pip install Django==$DJANGO --use-mirrors
  - pip install -q -e . --use-mirrors
  - pip install coveralls
# command to run tests
script:
  - coverage run --source=massadmin manage.py test
after_success:
  coveralls
sudo: false
