language: python

python:
  - "2.7"
  - "3.4"

env:
  - DJANGO=1.6
  - DJANGO=1.7
  - DJANGO=1.8

matrix:
  exclude:
    - python: "3.4"
      env: DJANGO=1.4

install:
  - pip install Django==$DJANGO --use-mirrors
  - pip install -e . --use-mirrors

script: python manage.py test --settings=tests.settings